stages:
- build
- deploy

build:
  stage: build
  when: on_success
  only:
    - master
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/jokoho482/mikerosdockertools .
    - docker push $CI_REGISTRY/jokoho482/mikerosdockertools

